version: '3.4'

services:
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pfopSDuTXh6Am5yLX7dyFcPWt
      - MYSQL_DATABASE=enrichment
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"

  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}big-data-analytics-api
    build: .
    ports:
      - "5555:5555"

  angular:
    container_name: angular
    image: ${DOCKER_REGISTRY-}big-data-analytics-angular
    build: ./analytics-frontend
    ports:
      - "4200:4000"